// API
const API_READY = 'API_READY';
const API_LOADING = 'API_LOADING';
const API_SUCCESS = 'API_SUCCESS';
const API_FAIL = 'API_FAILURE';

// Project
const FETCH_PROJECT = 'fetchProject';
const CLONE_PROJECT = 'cloneProject';

export {
	API_READY,
	API_LOADING,
	API_SUCCESS,
	API_FAIL,
	FETCH_PROJECT,
	CLONE_PROJECT
};
